name: CI/CD

on:
    push:
        branches:
            - main
            - develop
    pull_request:

permissions:
    contents: write
    deployments: write
    pages: write
    id-token: write

jobs:
    main:
        name: Test, build, and publish
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            # Check repo

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Restore cached deps
              id: cache-primes-restore
              uses: actions/cache/restore@v4
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                      /home/runner/.cache/ms-playwright
                  key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}-${{hashFiles('packages/**/package-lock.json') }}

            - name: Install root dependencies
              run: npm install

            - name: Save commit hash
              run: node scripts/store-commit-hash.mjs

            - name: Check each package has documentation, license, and Storybook files
              run: node scripts/check-documentation-files.mjs

            - name: Check if Storybook test results exist (not removed)
              run: node scripts/check-story-results.mjs

            # Cache Deps

            - name: Install package dependencies at root level (for Storybook)
              run: node scripts/install-deps-at-root.mjs

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Save deps to cache
              id: cache-primes-save
              uses: actions/cache/save@v4
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                      /home/runner/.cache/ms-playwright
                  key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}-${{hashFiles('packages/**/package-lock.json') }}

            # Test

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm install && node scripts/generate-storybook-docs.mjs

            - name: Run tests
              run: npm run test:ci

            - name: Check if Storybook test results exist (after testing)
              run: npm install && node scripts/check-story-results.mjs

            # Build

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            # Publish

            - name: Publish updated packages to JSR (dry-run, then push on main)
              if: github.ref == 'refs/heads/main'
              run: node scripts/publish-jsr.mjs

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main'
              run: node scripts/commit-push-diffs.mjs
