name: CI/CD

on:
    push:
        branches:
            - main
            - develop
    pull_request:

permissions:
    contents: write
    deployments: write
    pages: write
    id-token: write

jobs:
    main:
        name: Test, build, and publish
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            - name: Restore cached deps
              id: cache-primes-restore
              uses: actions/cache/restore@v4
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                  key: ${{ runner.os }}-${{github.ref}}-deps-${{ hashFiles('package.json') }}-${{hashFiles('packages/**/package.json') }}

            # Check repo

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install root dependencies
              run: npm install

            - name: Check each package has documentation, license, and Storybook files
              run: node scripts/check-documentation-files.mjs

            - name: Check if Storybook test results exist (not removed)
              run: node scripts/check-story-results.mjs

            # Cache Deps

            - name: Install package dependencies at root level (for Storybook)
              run: node scripts/install-deps-at-root.mjs
              
            - name: Get installed Playwright version
              id: playwright-version
              run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
            - name: Cache playwright binaries
              uses: actions/cache@v3
              id: playwright-cache
              with:
                path: |
                  ~/.cache/ms-playwright
                key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
            - run: npm ci
            - run: npx playwright install --with-deps
              if: steps.playwright-cache.outputs.cache-hit != 'true'
            - run: npx playwright install-deps
              if: steps.playwright-cache.outputs.cache-hit != 'true'

            - name: Save deps to cache
              id: cache-primes-save
              uses: actions/cache/save@v4
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                  key: ${{ runner.os }}-${{github.ref}}-deps-${{ hashFiles('package-lock.json') }}

            # Test

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm install && node scripts/generate-storybook-docs.mjs

            - name: Run tests
              run: npm run test:ci

            - name: Check if Storybook test results exist (after testing)
              run: npm install && node scripts/check-story-results.mjs

            # Build

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            # Publish

            - name: Generate publishing scripts
              id: generate-publish-scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: "[dry-run] Publish updated packages to JSR"
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main'
              run: bash scripts/publish-jsr.sh

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main'
              run: node scripts/commit-push-diffs.mjs
