name: CI/CD

on:
    push:
        branches:
            - main
            - develop
    pull_request:

jobs:
    main:
        name: Test, build, and publish
        timeout-minutes: 60
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.publish-storybook.outputs.page_url }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            # Check repo

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Check each package has documentation, license, and Storybook files
              run: node scripts/check-documentation-files.mjs

            - name: Check if Storybook stories results exist
              run: node scripts/check-story-results.mjs

            # Build

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Run tests
              run: npm run test:ci

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README and index.html file
              run: node scripts/generate-root-docs.mjs
            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm i && node scripts/generate-storybook-pkg-docs.mjs

            # Test

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Build, serve, and test Storybook
              run: npm run test:ci

            - name: Check if Storybook stories results exist
              run: npm i && node scripts/check-story-results.mjs

            # Publish

            - name: Generate publishing scripts
              id: generate-publish-scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: "[dry-run] Publish updated packages to JSR"
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main'
              run: bash scripts/publish-jsr.sh

            - name: Publish Storybook
              id: publish-storybook
              uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: yarn install # default: npm ci
                  build_command: yarn build-storybook:build # default: npm run build-storybook
                  path: storybook-static # default: dist/storybook
                  checkout: false # default: true

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main'
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -a -m "[GH Actions] Update documentation and package files" || exit 0
                  git push
