name: CI/CD

on:
    push:
        branches:
            - main
            - develop
    pull_request:

permissions:
    contents: write
    deployments: write
    pages: write
    id-token: write

jobs:
    main:
        name: Test, build, and publish
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Skip if commit message starts with [GH Actions]
              if: ${{ github.event.head_commit.message && startsWith(github.event.head_commit.message, '[GH Actions]') }}
              run: |
                  echo "[GH Actions] commit detected, skipping job."
                  exit 0

            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}
                  fetch-depth: 0

            # Check repo

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

            - name: Setup Node.js environment
              uses: actions/setup-node@v4

            - name: Handle cached deps
              id: cache-deps-restore
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                  key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}-pkg-${{hashFiles('packages/**/package-lock.json') }}

            - name: Install root dependencies
              run: npm i

            - name: Check each package has documentation, license, and Storybook files
              run: node scripts/check-documentation-files.mjs

            # Cache Deps

            - name: Install package dependencies at root level (for Storybook)
              run: node scripts/install-deps-at-root.mjs

            - name: Install Playwright
              run: npx playwright install --with-deps

            # Test

            - name: Run tests
              run: npm run test-ci

            # - name: Run Chromatic (on PRs)
            #   if: github.event_name == 'pull_request'
            #   uses: chromaui/action@latest
            #   with:
            #       projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

            - name: Check if Storybook test results exist after testing
              run: node scripts/check-story-results.mjs

            # Build

            - name: Bump versions in package.json files
              run: node scripts/bump-versions.mjs

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump autoloader package version
              run: node scripts/bump-versions.mjs

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: node scripts/generate-storybook-docs.mjs

            # Publish

            - name: Publish updated packages to JSR (dry-run, then push on main)
              run: node scripts/publish-jsr.mjs

            - name: Save commit hash
              run: node scripts/store-commit-hash.mjs

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main'
              run: node scripts/commit-push-diffs.mjs
