name: CI/CD

on:
    workflow_run:
        workflows: 
            - Repository
        types:
            - completed

jobs:
    main:
        name: Test, build, and publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            - name: build-storybook
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: npm run build-storybook
            
            - name: Install Playwright
              needs: build-storybook
              run: npx playwright install --with-deps

            - name: Serve Storybook and run tests
              run: |
                npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                "npx http-server storybook-static --port 6006 --silent" \
                "npx wait-on tcp:6006 && npm run test"

            - name: Generate publishing scripts
              id: generate-publish-scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: "[dry-run] Publish updated packages to JSR"
              needs: generate-publish-scripts
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              needs: generate-publish-scripts
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: bash scripts/publish-jsr.sh

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] Update documentation" || exit 0
                  git push
