name: CI/CD

on:
    push:
    pull_request:

jobs:
    main:
        name: Test, build, and publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            # Check repo
          
            - name: check-codeowners
              run: bash scripts/check-codeowners.sh

            - name: Check each package has documentation file
              run: bash scripts/check-documentation.sh

            - name: Check if LICENSE files exist
              run: bash scripts/check-licenses.sh

            - name: Check if Storybook stories exist
              run: npm i && node scripts/check-stories.mjs

            - name: Check if Storybook stories results exist
              run: npm i && node scripts/check-story-results.mjs

            # Build

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs
            
            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm i && node scripts/generate-storybook-pkg-docs.mjs

            - name: build-storybook
              run: npm run build-storybook

            # Test
            
            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Serve Storybook and run tests
              run: |
                npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                "npx http-server storybook-static --port 6006 --silent" \
                "npx wait-on tcp:6006 && npm run test"

            # Publish

            - name: Generate publishing scripts
              id: generate-publish-scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: "[dry-run] Publish updated packages to JSR"
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main'
              run: bash scripts/publish-jsr.sh

            # Save file changes

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main'
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] Update documentation" || exit 0
                  git push
