name: CI/CD

on:
    push:
        branches:
            - main
            - develop
    pull_request:

jobs:
    main:
        name: Test, build, and publish
        timeout-minutes: 60
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.publish-storybook.outputs.page_url }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            - name: Restore cached deps
              id: cache-primes-restore
              uses: actions/cache/restore@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-${{github.ref}}-deps-${{ hashFiles('package.json') }}-${{hashFiles('**/package.json') }}

            # Check repo

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install root dependencies
              run: npm install

            - name: Check each package has documentation, license, and Storybook files
              run: node scripts/check-documentation-files.mjs

            - name: Check if Storybook test results exist (not removed)
              run: node scripts/check-story-results.mjs

            # Cache Deps

            - name: Install package dependencies at root level (for Storybook)
              run: node scripts/install-deps-at-root.mjs

            - name: Install Playwright
              run: npx playwright install --with-deps

            - name: Save deps to cache
              id: cache-primes-save
              uses: actions/cache/save@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-${{github.ref}}-deps-${{ hashFiles('package.json') }}-${{hashFiles('**/package.json') }}

            # Test

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm install && node scripts/generate-storybook-pkg-docs.mjs

            - name: Run tests
              run: npm run test:ci

            - name: Check if Storybook test results exist (after testing)
              run: npm install && node scripts/check-story-results.mjs

            # Build

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            # Publish

            - name: Generate publishing scripts
              id: generate-publish-scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: "[dry-run] Publish updated packages to JSR"
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main'
              run: bash scripts/publish-jsr.sh

            - name: Check file diff
              id: check-file-diff
              if: github.ref == 'refs/heads/main'
              run: |
                  # Diff HEAD with the previous commit
                  $diff = git diff --name-only HEAD^ HEAD
                  # ignore the storybook-static/project.json file
                  $SourceDiff = $diff | Where-Object { $_ -ne '/storybook-static/project.json' }
                  $HasDiff = $SourceDiff.Length -gt 0
                  # Set the output named "files_changed"
                  Write-Host "::set-output name=files_changed::$HasDiff"

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main' && steps.check-file-diff.outputs.files_changed == 'true'
              run: |
                  $diff = git diff --name-only HEAD^ HEAD
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -a -m "[GH Actions] Update documentation and package files" || exit 0
                  git push
