name: CI/CD

on:
    workflow_run:
        workflows: [Repository]
        branches: [main]
        types:
            - completed

jobs:
    main:
        name: Test, build, and publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}
            - uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: /**

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in changed packages
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR config from package.json files
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            - name: Generate publishing scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: "[dry-run] Publish updated packages to JSR"
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: bash scripts/publish-jsr.sh

            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] Update documentation" || exit 0
                  git push

            - name: Deploy to GitHub Pages
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              id: deployment
              uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
              with:
                  token: ${{ secrets.CI_PAT }}
