name: CI/CD

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "packages/**"
            - "scripts/**"
    pull_request:
        paths:
            - ".github/workflows/**"
            - "packages/**"
            - "scripts/**"

jobs:
    main:
        name: Test
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                node-version: "20"

            - name: Install Jest
              run: npm install -g jest

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: node scripts/test-json.mjs

            - name: Build the autoloader package list
              run: node scripts/generate-autoloader-list.mjs

            - name: Bump versions in package.json files
              if: github.ref == 'refs/heads/main'
              run: bash scripts/bump-versions.sh

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            - name: Generate publishing scripts
              run: node scripts/generate-publish-scripts.mjs

            - name: Publish updated packages to JSR (dry-run)
              if: github.ref != 'refs/heads/main'
              run: bash scripts/publish-jsr-dryrun.sh

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main'
              run: bash scripts/publish-jsr.sh

            - name: Save test results (diff)
              run: |
                git diff
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git commit -am "[GH Actions] Update documentation" || exit 0
                git push
