name: Publish
on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish packages
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish
                      cd ..
                    fi
                  done
