name: Publish
on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Publish packages
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish
                      cd ..
                    fi
                  done
