name: Repository

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    check-files:
        name: Check files - CODEOWNERS, DOCUMENTATION, LICENSE, Storybook
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: check-codeowners
              run: bash scripts/check-codeowners.sh

            - name: Check each package has documentation file
              run: bash scripts/check-documentation.sh

            - name: Check if LICENSE files exist
              run: bash scripts/check-licenses.sh

            - name: Check if Storybook stories exist
              run: npm i && node scripts/check-stories.mjs

            - name: Check if Storybook stories results exist
              run: npm i && node scripts/check-story-results.mjs
    
    generate-sb-docs:
        name: Generate Storybook documentation
        needs: [check-files]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm i && node scripts/generate-storybook-pkg-docs.mjs
            
            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] Update documentation" || exit 0
                  git push

            