name: Repository

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    check-codeowners:
        name: CODEOWNERS file exists
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

    check-documentation:
        name: Documentation files exist
        needs: check-codeowners
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check each package has documentation file
              run: bash scripts/check-documentation.sh

    check-license:
        name: License files exists
        needs: check-codeowners
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check if LICENSE file exists
              run: bash scripts/check-licenses.sh
    
    check-stories:
        name: Storybook stories exist
        needs: check-codeowners
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check if Storybook stories exist
              run: npm i && node scripts/check-stories.mjs
    
    generate-sb-docs:
        name: Generate Storybook documentation
        needs: [check-documentation, check-license]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.CI_PAT }}

            - name: Generate Storybook documentation
              id: generate-storybook-docs
              run: npm i && node scripts/generate-storybook-pkg-docs.mjs
            
            - name: Save file changes (on main)
              if: github.ref == 'refs/heads/main' && ${{ github.event.workflow_run.conclusion == 'success' }}
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] Update documentation" || exit 0
                  git push

    check-story-results:
        name: Storybook stories test results exist
        needs: check-codeowners
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check if Storybook stories results exist
              run: npm i && node scripts/check-story-results.mjs