name: Repository

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    check-codeowners:
        name: CODEOWNERS file exists
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check if CODEOWNERS file exists
              run: bash scripts/check-codeowners.sh

    check-documentation:
        name: Documentation files exist
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check each package has documentation file
              run: bash scripts/check-documentation.sh
