name: Generate Documentation and Publish Packages

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run generate-autoloader.mjs script
              run: node scripts/generate-autoloader.mjs

            - name: Run generate-jsr.mjs script
              run: node scripts/generate-jsr.mjs

            - name: Run generate-root-readme.mjs script
              run: node scripts/generate-root-readme.mjs

            - name: Run generate-pkg-readmes.mjs script
              run: node scripts/generate-pkg-readmes.mjs

            - name: Commit and push changed files to repo
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] updated readme and/or config files" || exit 0
                  git push

            - name: Publish updated packages to JSR
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish --allow-dirty
                      cd ..
                    fi
                  done
