name: Test, Docs, & Publish

on: [push, pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    bump-versions:
        name: Bump package patch versions
        needs: [test]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Bump versions in package.json files
              run:

            - name: Commit and push changes
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] Bump patch versions" || exit 0
                  git push

    build-docs:
        name: Build docs
        needs: [test, bump-versions]
        if: always() #always run this job, but after bump-versions-on-main
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Generate JSR files from package.json
              run: node scripts/generate-jsr.mjs

            - name: Generate package README files
              run: node scripts/generate-pkg-readmes.mjs

            - name: Generate root README file
              run: node scripts/generate-root-readme.mjs

            - name: Generate the autoloader package
              run: node scripts/generate-autoloader.mjs

            - name: Commit and push changed files to repo
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] updated readme and/or config files" || exit 0
                  git push

    publish:
        name: Publish packages
        needs: [test, bump-versions, build-docs]
        runs-on: ubuntu-latest
        if: always() #always run this job, but after others
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish updated packages to JSR (dry-run)
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish --allow-dirty --dry-run
                      cd ..
                    fi
                  done

            - name: Publish updated packages to JSR (on main)
              if: github.ref == 'refs/heads/main'
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish --allow-dirty
                      cd ..
                    fi
                  done
