name: Generate Documentation and Publish Packages

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    bump-versions:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Bump version in package.json
              run: |
                  for dir in $(find . -name 'package.json' -printf '%h\n' | sort -u)
                  do
                    cd $dir
                    npm version patch -m "Bump package patch version"
                    cd ..
                  done

            - name: Commit and push changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -am "Bump version"
                  git push

    build-docs:
        needs: [test, bump-versions]
        if: always() #always run this job, but after bump-versions-on-main
        runs-on: ubuntu-latest

        permissions:
            contents: write
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run generate-autoloader.mjs script
              run: node scripts/generate-autoloader.mjs

            - name: Run generate-jsr.mjs script
              run: node scripts/generate-jsr.mjs

            - name: Run generate-root-readme.mjs script
              run: node scripts/generate-root-readme.mjs

            - name: Run generate-pkg-readmes.mjs script
              run: node scripts/generate-pkg-readmes.mjs

            - name: Commit and push changed files to repo
              run: |
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "[GH Actions] updated readme and/or config files" || exit 0
                  git push

    publish:
        needs: [test, bump-versions, build-docs]
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish updated packages to JSR (dry-run)
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish --allow-dirty --dry-run
                      cd ..
                    fi
                  done

            - name: Publish updated packages to JSR
              if: github.ref == 'refs/heads/main'
              run: |
                  for dir in packages/*; do
                    if [ -d "$dir" ]; then
                      cd "$dir"
                      npx jsr publish --allow-dirty
                      cd ..
                    fi
                  done
